PACKAGE_MAP = {
    "git": {
        "pacman": "git", "apt": "git", "dnf": "git",
        "yum": "git", "zypper": "git", "xbps-install": "git", "apk": "git",
    },
    "curl": {
        "pacman": "curl", "apt": "curl", "dnf": "curl",
        "yum": "curl", "zypper": "curl", "xbps-install": "curl", "apk": "curl",
    },
    "wget": {
        "pacman": "wget", "apt": "wget", "dnf": "wget",
        "yum": "wget", "zypper": "wget", "xbps-install": "wget", "apk": "wget",
    },
    "vscode": {
        "yay (AUR)": "visual-studio-code-bin",
        "paru (AUR)": "visual-studio-code-bin",
        "flatpak": "com.visualstudio.code",
    },
    "starship": {
        "pacman": "starship",
        "yay (AUR)": "starship",
        "paru (AUR)": "starship",
        "dnf": "starship",
        "zypper": "starship",
        "apk": "starship",
        "flatpak": "sh.starship.Starship",
        "__curl__": "https://starship.rs/install.sh",
    },
    "jetbrains-mono-nerd": {
        "pacman": "ttf-jetbrains-mono-nerd",
        "yay (AUR)": "ttf-jetbrains-mono-nerd",
        "paru (AUR)": "ttf-jetbrains-mono-nerd",
        "apt": "fonts-jetbrains-mono",
        "dnf": "jetbrains-mono-fonts",
        "zypper": "jetbrains-mono-fonts",
        "__manual__": True,
    },
    "discord": {
        "yay (AUR)": "discord",
        "paru (AUR)": "discord",
        "flatpak": "com.discordapp.Discord",
    },
    "spotify": {
        "yay (AUR)": "spotify",
        "paru (AUR)": "spotify",
        "flatpak": "com.spotify.Client",
    },
    "steam": {
        "pacman": "steam",
        "apt": "steam",
        "dnf": "steam",
        "zypper": "steam",
        "flatpak": "com.valvesoftware.Steam",
    },
    "postman": {
        "yay (AUR)": "postman-bin",
        "paru (AUR)": "postman-bin",
        "flatpak": "com.getpostman.Postman",
    },
    "notion": {
        "yay (AUR)": "notion-app-electron",
        "paru (AUR)": "notion-app-electron",
        "flatpak": "io.notion.Notion",
    },
    "obsidian": {
        "pacman": "obsidian",
        "yay (AUR)": "obsidian",
        "paru (AUR)": "obsidian",
        "dnf": "obsidian",
        "flatpak": "md.obsidian.Obsidian",
    },
    "teams": {
        "yay (AUR)": "teams-for-linux",
        "paru (AUR)": "teams-for-linux",
        "flatpak": "com.github.IsmaelMartinez.teams_for_linux",
    },
    "opera-gx": {
        "yay (AUR)": "opera-gx",
        "paru (AUR)": "opera-gx",
        "flatpak": "com.opera.opera-gx",
    },
    "heroic": {
        "yay (AUR)": "heroic-games-launcher-bin",
        "paru (AUR)": "heroic-games-launcher-bin",
        "flatpak": "com.heroicgameslauncher.hgl",
    },
    "lutris": {
        "pacman": "lutris",
        "yay (AUR)": "lutris",
        "paru (AUR)": "lutris",
        "apt": "lutris",
        "dnf": "lutris",
        "zypper": "lutris",
        "flatpak": "net.lutris.Lutris",
    },
}